#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Sensor, S4,     us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//setMotorSpeed(lm, 30);
	//setMotorSpeed(rm, -30);
	//sleep(1000);

	while(1){
		if(getTouchValue(ts)==1) {
			if(getColorReflected(cs) < 30) {
				setMotorSpeed(lm, 30);
				setMotorSpeed(rm, -30);
				sleep(2000);
				setMotorSpeed(lm, 0);
				setMotorSpeed(rm, 0);
				playSound(soundBeepBeep);
			}

		}
		else{
			setMotorSpeed(lm, 30);
				setMotorSpeed(rm, 30);
				sleep(1000);
				setMotorSpeed(lm, -30);
				setMotorSpeed(rm, -30);
				sleep(1000);
				setMotorSpeed(lm, 0);
				setMotorSpeed(rm, 0);
				playSound(soundBlip);
		}
	}

}
