#pragma config(Sensor, S4,     us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//setMotorSpeed(lm, 30);
	//setMotorSpeed(rm, -30);
	//sleep(1000);

	while(!1){
		if(getUSDistance(us)<10) {
			setMotorSpeed(lm, 30);
			setMotorSpeed(rm, -30);
			sleep(1000);
		}
		else if(getUSDistance(us)<30) {
			setMotorSpeed(lm, 30);
			setMotorSpeed(rm, 30);
			//sleep(1000);
		}
		else{
			setMotorSpeed(lm, 50);
			setMotorSpeed(rm, 50);
			//sleep(1000);
		}
	}

}
