#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	if(getTouchValue(ts)==1) {
		setMotorSpeed(lm, -30);
		setMotorSpeed(rm, -30);
		// run
		sleep(3000);
	}
	//else {
	//	setMotorSpeed(lm, 30);
	//	setMotorSpeed(rm, 30);
	//	// run
	//	sleep(3000);
	//}


}
