#pragma config(Sensor, S1, ts, sensorEV3_Touch)
#pragma config(Sensor, S2, gs, sensorEV3_Gyro)
#pragma config(Sensor, S3, cs, sensorEV3_Color)
#pragma config(Sensor, S4, us, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*/

#define MOTOR 50

task main()
{
	setMotorSpeed(lm, MOTOR);
	setMotorSpeed(rm, MOTOR);

	// run
	sleep(3000);
}
