#pragma config(Sensor, S4,     ss,             sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int dist, pos_x=1;

	while(1) {
		if(pos_x > 178)
		{
			eraseDisplay();
			pos_x=1;
		}
		dist = getUSDistance(ss)/3;
		drawLine(pos_x, 0, pos_x, dist);
		sleep(200);
		pos_x += 2;
	}
}
