#pragma config(Sensor, S1, ts, sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int num= 0;

	displayTextLine(1,"When you are ready,");
	displayTextLine(2,"press the touch sensor.");

	while(getTouchValue(ts)==0){}
	while(getTouchValue(ts)==1){
		num++;
		eraseDisplay();
		displayBigTextLine(4,"%d", num);
		sleep(100);
	}

	if(num==50){
		eraseDisplay();
		displayBigTextLine(4,"You WIN!!");
		playSound(soundUpwardTones);
		sleep(5000);
	}
}
