#pragma config(Sensor, S4,     ss,             sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	playSound(soundBeepBeep);
	sleep(2000);
	playSound(soundException);
	sleep(2000);

}
