#pragma config(Sensor, S3, cs, sensorEV3_Color)
#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

task main()
{
	int col;
	while(1){
		col = getColorReflected(cs);
		playImmediateTone(col*10, 50);
		sleep(500);

		setMotorSpeed(lm, col);
	  setMotorSpeed(rm, col);
		//sleep(500);
	}

	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);

}
