#pragma config(Sensor, S2, gs, sensorEV3_Gyro)
#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*/

task main()
{
	int speed_l, speed_r, curval;
	int initval = getGyroDegrees(gs); // initial gs value
	while(1){
		curval= getGyroDegrees(gs)-initval;
		speed_l=15-curval;
		speed_r=15+curval;
		setMotorSpeed(lm, speed_l);
		setMotorSpeed(rm, speed_r);
	}

}
