#pragma config(Sensor, S1, ts, sensorEV3_Touch)
#pragma config(Motor,  motorB, lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC, rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 30;

	while(1){
		setMotorSpeed(lm, speed);
		setMotorSpeed(rm, speed);
		while(getTouchValue(ts)==0){}
		while(getTouchValue(ts)==1){}
		speed *= -1;

	}
}
