#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int search(int speed, int time);

task main()
{
	int lightValue;
	lightValue = search(50, 1000);

	displayBigTextLine(5, "Reflected light value : %d", lightValue);
	sleep(5000);
}

int search(int speed, int time)
{
	setMotorSpeed(lm,speed);
	setMotorSpeed(rm,speed);
	sleep(time);

	setMotorSpeed(lm,speed);
	setMotorSpeed(rm,speed);

	return getColorReflected(cs);

}
