#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S4,     us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define EDGE_VALUE 30

task main()
{
	while(getTouchValue(ts)==1)
	{
		if(getColorReflected(cs)<EDGE_VALUE){
			setMotorSpeed(lm, -50);
			setMotorSpeed(rm, 50);
		}
		if(getColorReflected(cs)>=EDGE_VALUE){
			setMotorSpeed(lm, 50);
			setMotorSpeed(rm, 50);
		}
	}
	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);
}
