#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = 3;
	int y = 6;

	if(x<5 && y<5) {
		playSound(soundBeepBeep);
		sleep(1000);
	}

	if(x<5 || y<5) {
		setLEDColor(ledOrangeFlash);   // ledOrangePulse
		sleep(1000);
	}

	if(!(x+y<5)){
		setMotorSpeed(lm, 30);
		setMotorSpeed(rm, 30);
		sleep(3000);
	}

}
