#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(getTouchValue(ts)==0);
	while(getTouchValue(ts)==1)
	{
		setMotorSpeed(lm, 0);
		setMotorSpeed(rm, 0);
		while(getColorReflected(cs)>40){
			setMotorSpeed(lm, 50);
			setMotorSpeed(rm, 50);
		}
	}

}
