#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Sensor, S4,     us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetMotorEncoder(lm);
	resetMotorEncoder(rm);

	while(getTouchValue(ts) == 0) {}
	while(getTouchValue(ts) == 1) {}

	setMotorSpeed(lm, 30);
	setMotorSpeed(rm, -30);
	sleep(5000);

	setMotorSpeed(lm, -30);
	setMotorSpeed(rm, 30);
	sleep(5000);

}
