#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*/

task main()
{
	resetMotorEncoder(lm);
	resetMotorEncoder(rm);

	setMotorTarget(lm, 1000, 20);
	setMotorTarget(rm, 1000, 20);

  waitUntilMotorStop(lm);
  resetMotorEncoder(lm);
	resetMotorEncoder(rm);

	setMotorTarget(lm, 1000, -20);
	setMotorTarget(rm, 1000, -20);

	waitUntilMotorStop(lm);

}
