#pragma config(Sensor, S2, gs, sensorEV3_Gyro)
#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int gyro_val;

	datalogOpen(0, 1, false);

	clearTimer(T1);

	while(time1[T1] < 5000)
	{
		setMotorSpeed(lm, 30);
		setMotorSpeed(rm, -30);
		gyro_val = getGyroDegrees(gs);
		datalogAddShort(0, gyro_val);
		sleep(200);
	}

	datalogClose();
}
