#pragma config(Sensor, S1, ts, sensorEV3_Touch)
#pragma config(Sensor, S2, gs, sensorEV3_Gyro)
#pragma config(Sensor, S3, cs, sensorEV3_Color)
#pragma config(Sensor, S4, us, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	datalogOpen(0, 4, false);

	clearTimer(T1);

	while(time1[T1] < 5000)
	{
		setMotorSpeed(lm, 30);
		setMotorSpeed(rm, -30);

		datalogAddShort(0, getTouchValue(ts));
		datalogAddShort(1, getGyroDegrees(gs));
		datalogAddShort(2, getColorReflected(cs));
		datalogAddShort(3, getUSDistance(us));
		sleep(200);
	}

	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);
	datalogClose();
}
