#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*/

int convert(int dist)
{
	return (int)(360.0 * dist / 17.58);
}

task main()
{
	int enc_degree;
	enc_degree = convert(25.0);

	resetMotorEncoder(lm);

	while(getMotorEncoder(lm) < enc_degree)
	{
		setMotorSpeed(lm, 50);
		setMotorSpeed(rm, 50);
	}

	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);

}
