#pragma config(Motor, motorB,lm, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC,rm, tmotorEV3_Large, PIDControl, driveRight, encoder)
/*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*/

task main()
{
	setMotorSyncTime(lm, rm, 0, 3000, 30);
	sleep(3000);

}
