#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Sensor, S4,     us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// ?Clear all datalog values that have not been read by the ROBOTC debugger
	datalogClear();

	// Start a group of datalog values
	//datalogDataGroupStart();
	//datalogBackgroundPollingResume();

	clearTimer(T1);

	while(time1[T1] < 10000)
	{
		setMotorSpeed(lm, 30);
		setMotorSpeed(rm, -30);

		datalogDataGroupStart();
		// Add the TS value to datalog series 1
		datalogAddValueWithTimeStamp(0, getTouchValue(ts));
		// Add the GS value to datalog series 2
		datalogAddValueWithTimeStamp(1, getGyroDegrees(gs));
		// Add the CS value to datalog series 3
		datalogAddValueWithTimeStamp(2, getColorReflected(cs));
		// Add the US value to datalog series 4
		datalogAddValueWithTimeStamp(3, getUSDistance(us));
		datalogDataGroupEnd();

		sleep(200);
	}

	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);

	//datalogBackgroundPollingPause();
	// End a group of datalog values
	//datalogDataGroupEnd();
}
