#pragma config(Sensor, S1,     ts,     sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,     sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Sensor, S3,     cs,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     us,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,  lm,   tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,  rm,   tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*//

#define None 0
#define Black 1
#define Blue 2
#define Green 3
#define Yellow 4
#define Red 5
#define White 6
#define Brown 7

int color;

task main()
{
	// check the color of the floor and traffic signs.
	string colorOfObject;
	//Keep looping forever
	//repeat(forever)
	while(1)
	{
		while(getTouchValue(ts)==1) {

			if(getColorName(cs) == colorRed)
			{
				//Store the text RED into the color string
				colorOfObject = "RED";
				color = Red;
				//break;
			}
			//If the color sensor plugged into port 3 returns
			// the colorBlue name (a Blue object is detected)
			else if(getColorName(cs) == colorGreen)
			{
				//Store the text GREEN into the color string
				colorOfObject = "GREEN";
				color = Green;
				//break;
			}
			else if(getColorName(cs) == colorBlue)
			{
				//Store the text Blue into the color string
				colorOfObject = "BLUE";
				color = Blue;
				//break;
			}
			else if(getColorName(cs) == colorYellow)
			{
				//Store the text YELLOW into the color string
				colorOfObject = "YELLOW";
				color = Yellow;
				//break;
			}
			else if(getColorName(cs) == colorBlack)
			{
				//Store the text Blue into the color string
				colorOfObject = "BLACK";
				color = Black;
				//break;
			}
			else if(getColorName(cs) == colorWhite)
			{
				//Store the text WHITE into the color string
				colorOfObject = "WHITE";
				color = White;
				//break;
			}
			else if(getColorName(cs) == colorBrown)
			{
				//Store the text BROWN into the color string
				colorOfObject = "BROWN";
				color = Brown;
				//break;
			}
			else
			{
				//Store the text NONE into the color string
				colorOfObject = "NONE";
				color = None;
				//break;
			}

			displayBigTextLine(3, "Color : %s", colorOfObject);
			displayBigTextLine(5, "Color # : %d", color);
			sleep(3000);
		} // end of while(getTouchValue(ts)==1)
	}   // end of while(1)
}     // main loop
