#pragma config(Sensor, S1, ts,	sensorEV3_Touch)
#pragma config(Sensor, S2, gs,	sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Sensor, S3, cs,	sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4, us,	sensorEV3_Ultrasonic)
#pragma config(Motor,	 motorB,	lm,	 tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,	 motorC,	rm,	 tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

#define None 0
#define Black 1
#define Blue 2
#define Green 3
#define Yellow 4
#define Red 5
#define White 6
#define Brown 7

int color;
int finish_line;
int speed = 30;
int start_val = 0;

void go(int s)
{
	setMotorSpeed(lm, s);
	setMotorSpeed(rm, s);
}

task main()
{
	while(getTouchValue(ts)==0){}
	while(getTouchValue(ts)==1){}  // start

	while(1)
	{
		color = getColorName(cs);
		go(speed);

		if(!start_val && (color != White))
		{
			finish_line = color;  // match the start and finish
			setLEDColor(ledGreen);
			sleep(700);
			start_val++;
			color = getColorName(cs);
		}

		// At finish line
		if(color == finish_line)
		{
			go(0);
			setLEDColor(ledRedPulse);
			//playSound(soundDownwardTones);
			sleep(500);
			break;  // Misssion completed!
		}

		// At Green
		if(color == Green)
		{
			playSound(soundBeepBeep);
			sleep(700);
		}

		// At Yellow
		if(color == Yellow)
		{






		}

		// AT Red
		if(color == Red)
		{





		}

		// AT Blue
		if(color == Blue)
		{





		}

	}

}
