#pragma config(Sensor, S1,		 ts,						 sensorEV3_Touch)
#pragma config(Sensor, S2,		 gs,						 sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Sensor, S3,		 cs,						 sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,		 us,						 sensorEV3_Ultrasonic)
#pragma config(Motor,	 motorB,					lm,						 tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,	 motorC,					rm,						 tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

#define None 0
#define Black 1
#define Blue 2
#define Green 3
#define Yellow 4
#define Red 5
#define White 6
#define Brown 7

int color;
int finish_line;
int speed = 30;
int start_val = 0;

void go(int s)
{
	setMotorSpeed(lm, s);
	setMotorSpeed(rm, s);
}

void putData(int color, int speed)
{
	int t = time1[T1];  // msec
	datalogAddShort(0, t);
	datalogAddShort(1, color);
	datalogAddShort(2, speed);
	sleep(50);
}

task main()
{
	while(getTouchValue(ts)==0){}
	while(getTouchValue(ts)==1){}  // start

	clearTimer(T1);  // initialization of timer

	datalogOpen(0, 3, false);  // time, color, speed

	while(1)
	{
		color = getColorName(cs);
		go(speed);

		putData(color, speed);

		if(!start_val && (color != White))
		{
			finish_line = color;  // match the start and finish
			setLEDColor(ledGreen);
			sleep(700);
			start_val++;
			color = getColorName(cs);
		}

		if(color == finish_line)
		{
			go(0);
			setLEDColor(ledRedPulse);
			playSound(soundDownwardTones);
			sleep(500);

			putData(color, 0);

			break;
		}

		if(color == Green)
		{
			playSound(soundBeepBeep);
			putData(color, speed);
			sleep(700);
		}

		if(color == Yellow)
		{
			go(speed/2);
			putData(color, speed/2);
			while(color == Yellow)
			{
				color = getColorName(cs);
				go(speed/2);
				playSound(soundLowBuzzShort);
				putData(color, speed/2);
				sleep(700);
			}
			go(speed);
		}

		if(color == Red)
		{
			go(0);
			putData(color, 0);
			sleep(1000);
			go(speed);
			putData(color, speed);
			sleep(700);
		}

		// AT Blue
		if(color == Blue)
		{
			go(speed*3/2);
			//for(int i=0;i<500/50;i++)
			//{
			//	putData(color, speed*3/2);
			//}
			putData(color, speed*3/2);
		}
	}

	datalogClose();

}
